ScanRegistration:
  ros__parameters:
    # switches
    # 0-horizon 2-mid360
    Lidar_Type: 2
    # lines used for lio, set to 1~6
    Used_Line: 4
    # 0(false) or 1(true)
    Feature_Mode: true
    # use segment algorithm
    Use_seg: false
    NumCurvSize: 2
    # [m]  <DistanceFaraway near / >DistanceFaraway far
    DistanceFaraway: 30.
    # nums of one part's flat featurel
    NumFlat: 3
    # nums of one scan's parts
    PartNum: 100
    # cloud curvature threshold of flat feature
    FlatThreshold: 0.02
    # break distance of break points
    BreakCornerDis: 1.
    # if(depth < LidarNearestDis) do not use this point
    LidarNearestDis: 1.0
    # corner filter threshold
    KdTreeCornerOutlierDis: 0.2
    map_skip_frame: 2
    # 0-custom msg ,1 ros sensor msg pointcloud2 msg
    msg_type: 0

PoseEstimation:
  ros__parameters:
    # 0-Not Use IMU, 1-Use IMU remove Rotation Distort, 2-Tightly Coupled IMU
    IMU_Mode: 2
    # Voxel Filter Size Use to Downsize Map Cloud
    filter_parameter_corner: 0.2
    filter_parameter_surf: 0.4
    # Extrinsic Parameter between Lidar & IMU
    Extrinsic_Tlb:
      [
        0.9999161,
        0.0026676,
        0.0126707,
        -0.011,
        -0.0025826,
        0.9999741,
        -0.0067201,
        -0.0234,
        -0.0126883,
        0.0066868,
        0.9998971,
        0.044,
        0.0,
        0.0,
        0.0,
        1.0,
      ]
